use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct RegisteredModelSource {
    module: String,
    definition_const: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo manifest dir"));
    let source_path = manifest_dir.join("registry/models.json");
    println!("cargo:rerun-if-changed={}", source_path.display());

    let sources = load_sources(&source_path);
    validate_sources(&sources, &source_path);
    let generated = render_sources(&sources);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo out dir"));
    let output_path = out_dir.join("registry_models.rs");
    fs::write(&output_path, generated).expect("write generated registry models");
}

fn load_sources(path: &Path) -> Vec<RegisteredModelSource> {
    let contents = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("failed to read {}: {error}", path.display());
    });
    serde_json::from_str(&contents).unwrap_or_else(|error| {
        panic!("failed to parse {} as JSON: {error}", path.display());
    })
}

fn validate_sources(sources: &[RegisteredModelSource], path: &Path) {
    assert!(
        !sources.is_empty(),
        "{} must define at least one registered model",
        path.display()
    );

    let mut seen = std::collections::BTreeSet::new();
    for source in sources {
        assert!(
            !source.module.trim().is_empty(),
            "{} contains an empty module name",
            path.display()
        );
        assert!(
            !source.definition_const.trim().is_empty(),
            "{} contains an empty definition const name",
            path.display()
        );
        let key = (&source.module, &source.definition_const);
        assert!(
            seen.insert(key),
            "{} contains duplicate module/definition entries for {}::{}",
            path.display(),
            source.module,
            source.definition_const
        );
    }
}

fn render_sources(sources: &[RegisteredModelSource]) -> String {
    let mut output = String::from("// @generated by build.rs; do not edit by hand.\n\n");

    write!(
        output,
        "/// Structured source data for statically registered models.\n\
         pub const REGISTERED_MODEL_DEFINITIONS: [RegisteredModelDefinition; {}] = [\n",
        sources.len()
    )
    .expect("write generated registry definitions");
    for source in sources {
        writeln!(
            output,
            "    {}::{},\n",
            source.module, source.definition_const
        )
        .expect("write generated registry definition source");
    }
    output.push_str("];\n\n");

    write!(
        output,
        "/// Registry entries exposed to identification and validation.\n\
         pub const MODEL_REGISTRY: [&ModelRegistryEntry; {}] = [\n",
        sources.len()
    )
    .expect("write generated model registry");
    for (index, _) in sources.iter().enumerate() {
        writeln!(
            output,
            "    REGISTERED_MODEL_DEFINITIONS[{index}].registry,"
        )
        .expect("write generated model registry entry");
    }
    output.push_str("];\n\n");

    write!(
        output,
        "/// Catalog entries exposed to model resolution and host surfaces.\n\
         pub const MODEL_CATALOG: [ModelCatalogEntry; {}] = [\n",
        sources.len()
    )
    .expect("write generated model catalog");
    for (index, _) in sources.iter().enumerate() {
        writeln!(
            output,
            "    REGISTERED_MODEL_DEFINITIONS[{index}].catalog_entry(),"
        )
        .expect("write generated model catalog entry");
    }
    output.push_str("];\n\n");

    write!(
        output,
        "/// Session constructors keyed by the generated model catalog.\n\
         pub const SESSION_REGISTRATIONS: [SessionRegistration; {}] = [\n",
        sources.len()
    )
    .expect("write generated session registrations");
    for (index, _) in sources.iter().enumerate() {
        writeln!(
            output,
            "    REGISTERED_MODEL_DEFINITIONS[{index}].session_registration(),"
        )
        .expect("write generated session registration entry");
    }
    output.push_str("];\n");

    output
}
