[package]
name = "cutout-protocols"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Protocol scaffolding for NOSFET Aero and Begode Falcon devices"
readme = "../../README.md"
keywords = ["ble", "pev", "aero", "falcon"]
categories = ["hardware-support", "embedded"]
build = "build.rs"

[lints]
workspace = true

[dependencies]
arrayvec.workspace = true
bitflags.workspace = true
bytes.workspace = true
crc32fast.workspace = true
cutout-core = { path = "../cutout-core", version = "0.1.0" }
thiserror.workspace = true
vesc.workspace = true

[dev-dependencies]
hex-literal.workspace = true
proptest.workspace = true

[build-dependencies]
serde.workspace = true
serde_json.workspace = true

[features]
default = []
dangerous-controls = []
