[toolchain]
channel = "1.99.0"
profile = "minimal"
components = [
    "clippy",
    "rust-src",
    "rustfmt",
    "rust-analyzer",
    "llvm-tools-preview",
]
targets = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-linux-android",
]
