[package]
name = "cutout-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for Cutout"
readme = "../../README.md"
keywords = ["ble", "pev", "cli"]
categories = ["command-line-utilities", "hardware-support"]

[lints]
workspace = true

[[bin]]
name = "cutout"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
cutout-btle = { path = "../cutout-btle", version = "0.1.0" }
cutout-core = { path = "../cutout-core", version = "0.1.0", features = ["serde"] }
cutout-protocols = { path = "../cutout-protocols", version = "0.1.0" }
ratatui.workspace = true
serde_json.workspace = true
signal-hook.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
btleplug.workspace = true
bytes.workspace = true
hex-literal.workspace = true
